name: learn-github-action
run-name: ${{ github.actor }} is learning github
on: [push]
jobs:
  this-is-first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      
  


